[package]
name = "wrenched"
version = "0.1.0"
edition = "2021"

[dependencies]
ropey = "1.6.1"
crop = { version = "0.4.2", features = ["graphemes"] }
vello = "0.2.1"
winit = "0.30.4"
xilem = { git = "https://github.com/linebender/xilem", rev = "ee3126139fb162c1f051d8af227f3e88fa615931" }
masonry = { git = "https://github.com/linebender/xilem", rev = "ee3126139fb162c1f051d8af227f3e88fa615931" }
accesskit = "0.16"
tracing = "0.1"
parley = "0.1"
eyre = "0.6.12"
smallvec = "1.13.2"

[[bin]]
name = "wrenched"
path = "app/main.rs"
