permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: build
jobs:
  nightly-build:
    name: rust-nightly build
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo build --release --all-targets
        run: cargo build --release --all-targets --locked
      - uses: actions/upload-artifact@v4
        with:
          name: wrenched-${{ matrix.os }}
          path: target/release/wrenched
          if-no-files-found: error
